{
 "title": "Docker Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_time * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} - node_boot_time * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) / count(node_time * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[1m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) * 100 / scalar(count(node_cpu{mode=\"user\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_memory_SwapFree * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_free{device=\"overlay\",fstype=\"overlay\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) / count(node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes (in runnable state)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_procs_running * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "running"
    },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(node_intr[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu[1m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) - (node_memory_MemFree * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} + node_memory_Buffers * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} + node_memory_Cached * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemFree * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(node_memory_Buffers * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "sum(node_memory_Cached * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_bytes_read{device=~\"[sv]da\"}[1m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_bytes_written{device=~\"[sv]da\"}[1m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_ms{device!~\"(rbd.*|md\\\\d+$)\"}[1m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{device!=\"lo\"}[1m]) * on(instance) group_left(nodename)node_uname_info{nodename=~\"^$instance$\"}",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes{device!=\"lo\"}[1m]) * on(instance) group_left(nodename)node_uname_info{nodename=~\"^$instance$\"}",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} - node_memory_SwapFree * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_SwapFree * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_vmstat_pswpin[1m]) * 4096 or irate(node_vmstat_pswpin[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} * 4096)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(node_vmstat_pswpout[1m]) * 4096 or irate(node_vmstat_pswpout[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"} * 4096)",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}