{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",instance=~\"^$instance$\"}[1m])) / count(node_cpu{mode=\"user\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) - sum((node_memory_MemFree+node_memory_Buffers+node_memory_Cached) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) ) / sum(node_memory_MemTotal * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device=\"overlay\",fstype=\"overlay\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) - sum(node_filesystem_free{device=\"overlay\",fstype=\"overlay\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})) / sum(node_filesystem_size{device=\"overlay\",fstype=\"overlay\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=~\"^$instance$\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"}) / count(node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_bytes_read{device=~\"[sv]da\"}[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_bytes_written{device=~\"[sv]da\"}[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_ms{device!~\"(rbd.*|md\\\\d+$)\"}[5m]) * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!~\"^(|.*pause.*)$\",instance=~\"^$instance$\"}[1m])) / scalar(count(node_cpu{mode=\"user\"} * on(instance) group_left(nodename) node_uname_info{nodename=~\"^$instance$\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!~\"^(|.*pause.*)$\",instance=~\"^$instance$\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!~\"^(|.*pause.*)$\",instance=~\"^$instance$\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}