{
 "title": "Kubernetes Pod Resources",
 "description": "Shows resource usage of Kubernetes pods.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image=~\".*pause.*\",instance=~\"^$instance$\"}) > 0)",
     "legendFormat": "pods"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,instance)",
     "legendFormat": "{{ instance }}/{{ pod_name }}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image=\"\",id!=\"/\",id!=\"/docker\",id!=\"/system.slice\",instance=~\"^$instance$\"}[1m])) by (id,instance)",
     "legendFormat": "{{ instance }}{{ id }}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name,instance)",
     "legendFormat": "{{ instance }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum (irate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,instance)",
     "legendFormat": "{{ instance }}/{{ pod_name }} < in"
    },
    {
     "expr": "- sum (irate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name,instance)",
     "legendFormat": "{{ instance }}/{{ pod_name }} > out"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name,instance)",
     "legendFormat": "{{ instance }}/{{ pod_name }}"
    }
   ]
  }
 ]
}