apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
data:
{{ (.Files.Glob "imports/*").AsConfig | indent 2 }}
