apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
{{- if .Values.selectPort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
{{ include "labels.core" . | indent 4 }}
